# Generated by Django 5.0.1 on 2024-01-11 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emsapp', '0002_employee_bonus_alter_employee_hire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(),
        ),
    ]
